name: self-hosted-runner example

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo "Running on self-hosted runner!"
